In [1]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [17]:
env = gym.make("FrozenLake-v0")
action_space_size = env.action_space.n
state_space_size = env.observation_space.n 
q_table = np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [22]:
num_episodes = 10000
max_steps_per_episode=100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1 
min_exploration_rate = 0.01
exploration_rate_decay = 0.001

rewards_all_episodes = []

#q-learning algorithm
for episodes in range(num_episodes):
    state = env.reset()
    
    done=False
    rewards_current_episode = 0
    for step in range(max_steps_per_episode):
        
        #Exploration-Exploitation trade-off
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        
        #Update Q-Table for Q(s,a)
       # print("new_state: ",new_state, ", action:",action)
       # print("q_table[new_state,:]",q_table[new_state,:])
        q_table[state, action] = q_table[state,action] * (1-learning_rate) +\
            learning_rate*(reward+discount_rate*np.max(q_table[new_state,:]))
        
        state = new_state
        rewards_current_episode += reward
        
        if done == True:
            break

    #Exploration rate decay
    exploration_rate = min_exploration_rate +\
            (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_rate_decay*episodes)
    
    rewards_all_episodes.append(rewards_current_episode)
    
#Calculate and Print the Average Reward per Thousand Episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000
for r in rewards_per_thousand_episodes:
    print(count,":",str(sum(r/1000)))
    count += 1000
    
#Print update Q-Table
print("\n\n***************** Q-Table *****************\n")
print(q_table)


1000 : 0.060000000000000046
2000 : 0.19500000000000015
3000 : 0.4110000000000003
4000 : 0.5680000000000004
5000 : 0.6350000000000005
6000 : 0.6400000000000005
7000 : 0.6950000000000005
8000 : 0.7120000000000005
9000 : 0.6540000000000005
10000 : 0.6800000000000005


***************** Q-Table *****************

[[0.60791542 0.53221386 0.52911832 0.53087979]
 [0.27386898 0.30996834 0.28791727 0.54559407]
 [0.4073099  0.40439816 0.39898589 0.48876368]
 [0.29892672 0.26289927 0.33905843 0.47215906]
 [0.63012613 0.31324247 0.42037965 0.33666842]
 [0.         0.         0.         0.        ]
 [0.37720852 0.16089761 0.15346304 0.06619253]
 [0.         0.         0.         0.        ]
 [0.3676519  0.33319297 0.43126597 0.64827331]
 [0.45608364 0.69029939 0.40719403 0.31321277]
 [0.7204605  0.37068191 0.22236584 0.22824781]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.40505244 0.43473793 0.81489135 0.53721193]
 [0.72997927 0.88398265 0.75097